In [ ]:
#1.Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[1,4,6],
        [6,5,8],
        [3,5,7]])
mat2 = np.array([[1,3,7],
        [5,8,3],
        [8,4,9]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[1 4 6]
 [6 5 8]
 [3 5 7]]  and 

[[1 3 7]
 [5 8 3]
 [8 4 9]]  is 

[[ 2  7 13]
 [11 13 11]
 [11  9 16]] 


In [ ]:
#2.Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np

mat1 = np.array([[1,4,6],
        [3,7,4],
        [9,1,2]])
mat2 = np.array([[2,4,7],
        [5,6,8],
        [8,9,1]])

mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[1 4 6]
 [3 7 4]
 [9 1 2]]  and 

[[2 4 7]
 [5 6 8]
 [8 9 1]]  is 

[[70 82 45]
 [73 90 81]
 [39 60 73]] 


In [ ]:
#3.Write a Python Program to Transpose a Matrix?

In [6]:
def Matrix(n,v=0):
    M=[]             
    for i in range(n):
        
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def crMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def prMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 

def tpMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = crMatrix(n)

print("Display Array M1 In Matrix Form")
prMatrix(M1,n)

result = Matrix(n)
result = tpMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 2
Enter the element :
3
2
5
6
Display Array M1 In Matrix Form
3 2 
5 6 
Transposed Matrix
[3, 5]
[2, 6]


In [ ]:
#4.Write a Python Program to Sort Words in Alphabetic Order?

In [2]:
Arr = input("Enter string ")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string sk a bb
a
bb
sk


In [ ]:
#5.Write a Python Program to Remove Punctuation From a String?

In [3]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
arr = input("Enter a string with punctuations")


rem_punc = ""
for i in arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuationsi@am****skb
iamskb
